### ISSUE TITLE
Defect code 0084940100

### ISSUE THREAD

**Issue by Seth772** [Alex-Bond/bmw-recall-tool#5]

**Comment by Alex-Bond** [comment]
@Seth772 I tried to find it for a couple of days, but no luck. Can you please call your CA and ask to take a screenshot of the internal system with a code description?

**Comment by StevenLi1119** [comment]
Dear all
Hello, I am so sorry to disturb u guys. I am the customer of this car from China. I saw the car is keeping the status “193” from February to now. It is means It stayed in port for five whole months, and there is still is issue not closed. I wonder when the car can start delivery. Otherwise it will become a car of inventory.
Best regards
Steven
